### PR TITLE
Feature/feature model wizard sc7

### PR DESCRIPTION
**Pull request by DawidSA2017**
In this Story card, the feature model wizard is still available when only feature modelling is installed. (fm.ui and fm.core)

### CODE REVIEW

**Comment by DawidSA2017** [comment]
We tried to reproduce the exception but in our Linux we don't have that problem. So we can't check if its fixed now. Please check in your environment if the bug is fixed.

**Comment by Kogoro** [comment]
The problem should be solved through checking if an extension exists and when it exists it should be stripped, as the extension could be wrong (Extension is set on the second page).
Or did I misinterpret the change?

**Comment by DawidSA2017** [comment]
Hello, we've fixed the file exists bug, and the '.' bug.

**Comment by tthuem** [comment]
@Kogoro Why is this pull request not merged yet?

**Comment by Kogoro** [comment]
#638 implements the same functionality but is more complex. If we take the implementation of pull-request 638, we don't need this one.

**Comment by Kogoro** [comment]
Closing this request in favor of #638.

**Pull request closed without merging**
