### PR TITLE
Fixed #1046: Fixed inconsistent usage of configuration formats by com…

### LINKED ISSUE #1046: Product Generator not Working for FeatureHouse Examples
#### Prerequisitives
* **Eclipse Version:**  `2019-12 (4.14.0)`
* **FeatureIDE-Version:**  `3.6.2`
* **Operating system:** `Windows 10 Pro`
* **Java runtime used to run eclipse:** `openjdk 13.0.1`
* **FeatureIDE Composer:** `Feature House`
* **Git branch/Commit-ID:**  ``
* **Java compiler used to build the FeatureIDE plugin:** ``

### Issue description
When using the product generator option the folders generated contain only the configuration file, but none of the source code as generated when using the "set as current configuration" option.
The issue happens with both .xml and .config files as configurations, as shown in the image.

image

### PR DESCRIPTION
**Pull request by Subaro**
…posers

### CODE REVIEW

**Comment by Subaro** [comment]
@PaulWestphal Could you also check out the PR an test it locally?

**Comment by PaulWestphal** [comment]
There's a failing test (and it's not a GUI test), have you looked at that?

**Comment by Subaro** [comment]
> @PaulWestphal  
> 
> There's a failing test (and it's not a GUI test), have you looked at that?

Locally I don't get any test failures. On Travis the only failures is a GUI test:

`[INFO] de.ovgu.featureide.fm.gui-test ..................... FAILURE [12:01 min]`

**Comment by PaulWestphal** [comment]
Tested it locally as well and the tests work.

**Pull request merged**
