### PR TITLE
WIP: Provide CMake option composer as output for the FeatureIDE #570

### PR DESCRIPTION
**Pull request by niecore**
- Added CMake-Composer Plugin
- Added CMake-Composer Hello-World-Example

There is one open point in which I might need your help.

 Currently the build and binary folders are deleted before each new build. This is not usable for the CMake approach because "generator phase" of CMake takes 10-20 seconds to complete. It would be nice to keep these folders. That's why I added in ExtensibleFeatureProjectBuilder.java a private field to exclude the reset of these folders. Unfortunately I don't know how to access this option from the composer. It would be nice, if you could point to a scene where this could be set.

Thanks for your help.

### CODE REVIEW

**Comment by niecore** [comment]
@tthuem Any updates here?

**Comment by tthuem** [comment]
@niecore Had a brief look into the code and looks fine so far. Nevertheless, as a new composer is a quite large change, I would prefer if you could give us a demo (e.g., in the FeatureIDE meeting). Are you available next a wednesday at 3pm (Berlin) via Skype? If so, just add me in your Skype (tthuem).

**Comment by tthuem** [comment]
@niecore What is the status for this pull request. I remember that you planned to do some changes. Shall we close this pull request and you open a new one once you are done with those changes?

**Comment by niecore** [comment]
Yes @tthuem we can do it in that way. This anyhow only be completed when I get the "incremental build" interface for the composer from your upstream.

Any updates about that?

**Pull request closed without merging**
