### PR TITLE
Merge of fop-pullup-codeclones with develop

### PR DESCRIPTION
**Pull request by Adarsh-g-s**
This merge includes the CloneAnalysis composer from the fop-pullup-codeclones branch along with all the composers from the develop branch. 

--> Many rounds of unit tests have been performed. 
  Issues found: If "de.ovgu.featureide.core.featurehouse-test" fails in the rename refactoring case(then the unit test itself is broken) as the issue was not introduced due to the merge. 
  The unit test fails in fop-pullup-codeclones branch itself.

--> Many rounds of exploratory testing have been performed after the merge.
Issues Found: 4 issues were found both in the develop and the merge branch and the aforementioned issues have been raised recently.

### CODE REVIEW

**Comment by Adarsh-g-s** [comment]
*all composers in develop would mean all projects under the plugins folder of develop branch.

**Comment by Adarsh-g-s** [comment]
wfenske/FeatureIDE
Branch Names:
1- fop-pullup-codeclones - Contains CloneAnalysis and refactoring
2- merge - Merge of fop-pullup-codeclones and develop.

**Comment by tthuem** [comment]
@meinicke Any news on the failing test?

BTW: Please remember to not merge it into develop, but rather into a new branch.

**Comment by meinicke** [comment]
1) The tests [RenameClassRefactoringTest](https://github.com/wfenske/FeatureIDE/blob/merge/tests/de.ovgu.featureide.core.featurehouse-test/src/de/ovgu/featureide/featurehouse/refactoring/RenameClassRefactoringTest.java) and [RenameMethodRefactoringTest ](https://github.com/wfenske/FeatureIDE/blob/merge/tests/de.ovgu.featureide.core.featurehouse-test/src/de/ovgu/featureide/featurehouse/refactoring/RenameMethodRefactoringTest.java) seem to be Plugin Test as they require an open workspace and a feature project to run.
i.e., run as plugin test and open a workspace containing a project named "HelloWorld-FH-Java-Test"
2) They also require fuji, see [RenameRefactoringTest](https://github.com/wfenske/FeatureIDE/blob/merge/tests/de.ovgu.featureide.core.featurehouse-test/src/de/ovgu/featureide/featurehouse/refactoring/RenameRefactoringTest.java) Line 100, which calls [ExtendedFujiSignaturesJob](https://github.com/FeatureIDE/FeatureIDE/blob/develop/plugins/de.ovgu.featureide.core.featurehouse/src/de/ovgu/featureide/featurehouse/ExtendedFujiSignaturesJob.java)
This can however not work because this class is commented out, see this commit:
https://github.com/FeatureIDE/FeatureIDE/commit/5564449b8dad022d0ef1c77a8bc45590bda93c18

**Comment by tthuem** [comment]
Here is a summary of what we discussed in our meeting today.

Refactoring does not seem to work without having a working alternative for Fuji. Hence, it would be good to split the part on refactorings of that on clone analysis.

@Adarsh-g-s Please check whether it is feasible to separate both functionalities. Simply copy your clone analysis plug-in into a folder with the current develop and see whether it works. If not, what changes are necessary to our plug-ins?

**Comment by Adarsh-g-s** [comment]
Added the CloneAnalysis project to the develop folder and was able to run the CloneAnalysis project.
cloneanalysis_1

Below are the results.
cloneanalysis_2

This looks fine to me.

**Comment by tthuem** [comment]
Duplicate to #679

**Pull request closed without merging**
